#!/usr/bin/python3
def search_replace(my_list, search, replace):
    n = len(my_list)
    for i in range(n):
        if my_list[i] == search:
            my_list[i] = replace
            new_list = my_list[:i] + my_list[i:]
            my_list[i] = search
            return new_list
    new_list = my_list.copy()
    new_list.append(search)
    return new_list
